/** Catálogo de bicicletas MTB/Enduro (2016–2026) con especificaciones de serie */
export interface BikeModelSpec {
  name: string;
  year: number;
  weightKg: number;
  wheelFront: '29' | '27.5';
  wheelRear: '29' | '27.5';
  tireWidthFrontInch: number;
  tireWidthRearInch: number;
  tireModelFront: string;
  tireModelRear: string;
  tubeless: boolean;
}

export const BIKE_MODELS: BikeModelSpec[] = [
  // ── BULLS ──────────────────────────────────────────
  {
    name: 'Bulls E-stream EVO FRS3',
    year: 2016,
    weightKg: 24,
    wheelFront: '27.5',
    wheelRear: '27.5',
    tireWidthFrontInch: 2.6,
    tireWidthRearInch: 2.6,
    tireModelFront: 'Schwalbe Magic Mary',
    tireModelRear: 'Schwalbe Hans Dampf',
    tubeless: true,
  },
  {
    name: 'Bulls Copperhead',
    year: 2024,
    weightKg: 23,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Schwalbe Racing Ray',
    tireModelRear: 'Schwalbe Racing Ralph',
    tubeless: true,
  },
  {
    name: 'Bulls Sonic EVO',
    year: 2024,
    weightKg: 23,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Schwalbe Nobby Nic',
    tireModelRear: 'Schwalbe Racing Ralph',
    tubeless: true,
  },
  {
    name: 'Bulls Wild Cross',
    year: 2025,
    weightKg: 22,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Schwalbe Magic Mary',
    tireModelRear: 'Schwalbe Nobby Nic',
    tubeless: true,
  },
  {
    name: 'Bulls Phantom',
    year: 2026,
    weightKg: 24,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Schwalbe Magic Mary Super Trail',
    tireModelRear: 'Schwalbe Nobby Nic Super Trail',
    tubeless: true,
  },

  // ── CANYON ──────────────────────────────────────────
  {
    name: 'Canyon Spectral',
    year: 2024,
    weightKg: 15,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Canyon Strive',
    year: 2024,
    weightKg: 15.5,
    wheelFront: '29',
    wheelRear: '27.5',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Canyon Neuron',
    year: 2025,
    weightKg: 14,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Schwalbe Nobby Nic',
    tireModelRear: 'Schwalbe Racing Ralph',
    tubeless: true,
  },
  {
    name: 'Canyon Torque',
    year: 2025,
    weightKg: 16,
    wheelFront: '29',
    wheelRear: '27.5',
    tireWidthFrontInch: 2.6,
    tireWidthRearInch: 2.6,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Canyon Spectral CF',
    year: 2026,
    weightKg: 14.5,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Dissector EXO+',
    tubeless: true,
  },

  // ── CANNONDALE ──────────────────────────────────────
  {
    name: 'Cannondale Moterra Neo Carbon',
    year: 2024,
    weightKg: 24,
    wheelFront: '29',
    wheelRear: '27.5',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Cannondale Jekyll',
    year: 2024,
    weightKg: 15,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Cannondale Habit NEO',
    year: 2025,
    weightKg: 23,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Maxxis Rekon EXO',
    tireModelRear: 'Maxxis Rekon EXO',
    tubeless: true,
  },
  {
    name: 'Cannondale Moterra SL',
    year: 2025,
    weightKg: 20,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Schwalbe Magic Mary Super Trail',
    tireModelRear: 'Schwalbe Nobby Nic Super Trail',
    tubeless: true,
  },
  {
    name: 'Cannondale Jekyll LT',
    year: 2026,
    weightKg: 15.5,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.6,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },

  // ── MONDRAKER ──────────────────────────────────────
  {
    name: 'Mondraker Foxy',
    year: 2024,
    weightKg: 14.5,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Mondraker Crafty',
    year: 2024,
    weightKg: 24,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Mondraker Level',
    year: 2025,
    weightKg: 13,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Maxxis Rekon EXO',
    tireModelRear: 'Maxxis Rekon EXO',
    tubeless: true,
  },
  {
    name: 'Mondraker Neat',
    year: 2025,
    weightKg: 19,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Schwalbe Nobby Nic Super Trail',
    tireModelRear: 'Schwalbe Racing Ralph Super Trail',
    tubeless: true,
  },
  {
    name: 'Mondraker Foxy',
    year: 2026,
    weightKg: 14,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },

  // ── ORBEA ──────────────────────────────────────────
  {
    name: 'Orbea Rise',
    year: 2024,
    weightKg: 19,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Rekon EXO+',
    tubeless: true,
  },
  {
    name: 'Orbea Wild',
    year: 2024,
    weightKg: 24,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Schwalbe Magic Mary Super Trail',
    tireModelRear: 'Schwalbe Nobby Nic Super Trail',
    tubeless: true,
  },
  {
    name: 'Orbea Occam',
    year: 2025,
    weightKg: 14,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Maxxis Rekon EXO',
    tireModelRear: 'Maxxis Rekon EXO',
    tubeless: true,
  },
  {
    name: 'Orbea Rallon',
    year: 2025,
    weightKg: 14.5,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Orbea Wild',
    year: 2026,
    weightKg: 23,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Schwalbe Magic Mary Super Trail',
    tireModelRear: 'Schwalbe Nobby Nic Super Trail',
    tubeless: true,
  },

  // ── SANTA CRUZ ──────────────────────────────────────
  {
    name: 'Santa Cruz Bullit',
    year: 2023,
    weightKg: 25,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Santa Cruz Nomad',
    year: 2024,
    weightKg: 15.5,
    wheelFront: '29',
    wheelRear: '27.5',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Santa Cruz Megatower',
    year: 2024,
    weightKg: 16,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },
  {
    name: 'Santa Cruz Hightower',
    year: 2025,
    weightKg: 15,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Maxxis Minion DHF EXO+',
    tireModelRear: 'Maxxis Dissector EXO+',
    tubeless: true,
  },
  {
    name: 'Santa Cruz Bronson',
    year: 2025,
    weightKg: 15,
    wheelFront: '29',
    wheelRear: '27.5',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Maxxis Assegai EXO+',
    tireModelRear: 'Maxxis Minion DHR II EXO+',
    tubeless: true,
  },

  // ── SPECIALIZED ──────────────────────────────────────
  {
    name: 'Turbo Levo Carbono 2023',
    year: 2023,
    weightKg: 22,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.3,
    tireWidthRearInch: 2.3,
    tireModelFront: 'Butcher T9 GRID TRAIL',
    tireModelRear: 'Eliminator T7 GRID TRAIL',
    tubeless: true,
  },
  {
    name: 'Specialized Turbo Levo Comp',
    year: 2023,
    weightKg: 24,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.3,
    tireWidthRearInch: 2.3,
    tireModelFront: 'Butcher T9 GRID TRAIL',
    tireModelRear: 'Eliminator T7 GRID TRAIL',
    tubeless: true,
  },
  {
    name: 'Specialized Levo SL',
    year: 2024,
    weightKg: 18,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.3,
    tireWidthRearInch: 2.3,
    tireModelFront: 'Eliminator T7 GRID TRAIL',
    tireModelRear: 'Eliminator T7 GRID TRAIL',
    tubeless: true,
  },
  {
    name: 'Specialized Turbo Levo Pro',
    year: 2024,
    weightKg: 21,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.3,
    tireWidthRearInch: 2.3,
    tireModelFront: 'Butcher T9 GRID TRAIL',
    tireModelRear: 'Eliminator T7 GRID TRAIL',
    tubeless: true,
  },
  {
    name: 'Specialized Turbo Levo Carbon',
    year: 2025,
    weightKg: 22,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.3,
    tireWidthRearInch: 2.3,
    tireModelFront: 'Butcher T9 GRID TRAIL',
    tireModelRear: 'Eliminator T7 GRID TRAIL',
    tubeless: true,
  },

  // ── TREK ──────────────────────────────────────────
  {
    name: 'Trek Rail 9.8',
    year: 2024,
    weightKg: 24,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Bontrager SE5 Team Issue',
    tireModelRear: 'Bontrager SE6 Team Issue',
    tubeless: true,
  },
  {
    name: 'Trek Slash 9.9',
    year: 2024,
    weightKg: 16,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Bontrager SE5 Team Issue',
    tireModelRear: 'Bontrager SE6 Team Issue',
    tubeless: true,
  },
  {
    name: 'Trek Fuel EX 9.9',
    year: 2025,
    weightKg: 14,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.4,
    tireWidthRearInch: 2.4,
    tireModelFront: 'Bontrager SE5 Team Issue',
    tireModelRear: 'Bontrager SE5 Team Issue',
    tubeless: true,
  },
  {
    name: 'Trek Slash+',
    year: 2025,
    weightKg: 23,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Bontrager SE5 Team Issue',
    tireModelRear: 'Bontrager SE6 Team Issue',
    tubeless: true,
  },
  {
    name: 'Trek Rail 9.9',
    year: 2026,
    weightKg: 23,
    wheelFront: '29',
    wheelRear: '29',
    tireWidthFrontInch: 2.5,
    tireWidthRearInch: 2.5,
    tireModelFront: 'Bontrager SE6 Team Issue',
    tireModelRear: 'Bontrager SE5 Team Issue',
    tubeless: true,
  },
];
